version: '3.7'

services:
  nginx:
    build: ./.docker/nginx
    ports:
      - 80:80
    depends_on:
      - app
    volumes:
      - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./public:/app/public

  app:
    build: ./.docker/php
    working_dir: /app
    volumes:
      - .:/app:cached
      - ./.docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini
    depends_on:
      - mysql

  minio:
    image: minio/minio
    ports:
      - 9000:9000
    volumes:
      - ./storage/minio:/storage
    command: server /storage
    environment:
      MINIO_ACCESS_KEY: ${AWS_ACCESS_KEY_ID:-root}
      MINIO_SECRET_KEY: ${AWS_SECRET_ACCESS_KEY:-password}
      MINIO_REGION: ap-northeast-1
      MINIO_DEFAULT_BUCKETS: ${AWS_S3_BUCKET:-uploads:public,evidence-files:public}

  mysql:
    image: mysql:5.7
    ports:
      - 4306:3306
    volumes:
      - ./storage/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-laravel}
      MYSQL_USER: ${DB_USERNAME:-root}
      MYSQL_PASSWORD: ${DB_PASSWORD:-root}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-root}
